// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HomeWorkToDos.DataAccess.Models
{
    public partial class ToDoItem
    {
        [Key]
        public int ToDoItemId { get; set; }
        public int? ToDoListId { get; set; }
        public int? LabelId { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public int UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedOn { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(LabelId))]
        [InverseProperty("ToDoItem")]
        public virtual Label Label { get; set; }
        [ForeignKey(nameof(ToDoListId))]
        [InverseProperty("ToDoItem")]
        public virtual ToDoList ToDoList { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("ToDoItem")]
        public virtual User User { get; set; }
    }
}