// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HomeWorkToDos.DataAccess.Models
{
    public partial class User
    {
        public User()
        {
            Label = new HashSet<Label>();
            ToDoItem = new HashSet<ToDoItem>();
            ToDoList = new HashSet<ToDoList>();
        }

        [Key]
        public int UserId { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(10)]
        public string Contact { get; set; }
        [Required]
        [StringLength(50)]
        public string UserName { get; set; }
        [Required]
        [StringLength(50)]
        public string Password { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedOn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedOn { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Label> Label { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<ToDoItem> ToDoItem { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<ToDoList> ToDoList { get; set; }
    }
}